name = "the-coderz"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

# Set the desired Node.js version (e.g., v20)
[env]
NODE_VERSION = "20"

pages_build_output_dir = ".next/"
